import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/toaster";
import ServerIpProvider from "@/Providers/ServerIpProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ServerIpProvider>
          <div className="app_bg">
            <Navbar />
          </div>

          {children}
          <Toaster />
        </ServerIpProvider>
      </body>
    </html>
  );
}
